In [1]:
import numpy as np

In [2]:
a3 = np.array([[[20,30],[1,2]],[[101,102],[67,98]],[[22,22],[9,8]]])

In [3]:
a3

array([[[ 20,  30],
        [  1,   2]],

       [[101, 102],
        [ 67,  98]],

       [[ 22,  22],
        [  9,   8]]])

In [4]:
a3.ndim

3

In [5]:
a3[2,1,1]

8

In [6]:
a3.reshape(3,4,1) # 3 dimensions, 4 rows and 1 columns

array([[[ 20],
        [ 30],
        [  1],
        [  2]],

       [[101],
        [102],
        [ 67],
        [ 98]],

       [[ 22],
        [ 22],
        [  9],
        [  8]]])

In [7]:
a3.reshape(3,4,-1) # 3 dimensions, 4 rows and 1 columns [Here, the columns automatically get calculated when -1]

array([[[ 20],
        [ 30],
        [  1],
        [  2]],

       [[101],
        [102],
        [ 67],
        [ 98]],

       [[ 22],
        [ 22],
        [  9],
        [  8]]])

In [8]:
a3.reshape(2,3,-1) # 2-Dimension, 3-Rows, -1-Automatic calculation of columns

array([[[ 20,  30],
        [  1,   2],
        [101, 102]],

       [[ 67,  98],
        [ 22,  22],
        [  9,   8]]])

In [9]:
a3.reshape(3,4)

array([[ 20,  30,   1,   2],
       [101, 102,  67,  98],
       [ 22,  22,   9,   8]])

In [10]:
a3.reshape(-1,6) # -1-Automatic Row calculation, 6-Columns

array([[ 20,  30,   1,   2, 101, 102],
       [ 67,  98,  22,  22,   9,   8]])