In [1]:
import numpy as np

In [2]:
import os

In [3]:
os.getcwd()

'/drive/notebooks'

In [7]:
# reading a txt/csv file
data = np.loadtxt("Sample_File.csv", delimiter=",",dtype='str')

In [8]:
data

array([['\ufeffName', 'Age', 'Gender'],
       ['Nithin', '24', 'Male'],
       ['Manoj', '30', 'Male'],
       ['Shivshankar', '44', 'Male'],
       ['Swathi', '18', 'Female'],
       ['Pareekshith', '28', 'Male']], dtype='<U11')

In [9]:
#NOTE: Here on the top, we can see that the Age column is there as a item in the array and this cannot be used for File Handling on NumPy!

In [10]:
# ARGMAX & ARGMIN - Position of Max and Min value
x = np.array([12,67,98,3,2])

In [11]:
# Position of Max. value
np.argmax(x)

2

In [12]:
# Position of Min. value
np.argmin(x)

4

In [16]:
# Position of Max. and Min. value in a multidimensional array using AXIS
# Reference Link on how the axis works on Multi-dimensional Arrays: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

y = np.array([[0.5,0.4,0.1],[0.2,0.1,0.7]])

In [17]:
y

array([[0.5, 0.4, 0.1],
       [0.2, 0.1, 0.7]])

In [25]:
# axis = 1 ---> Apply calculation Row-wise ---> Here, finds the position of max value
np.argmax(y,axis=1)

array([0, 2], dtype=int32)

In [24]:
# axis = 0 ---> Apply calculation Column-wise ---> Here, finds the position of max value
np.argmax(y,axis=0)

array([0, 0, 1], dtype=int32)