##__NumPy Array Shapes and Axes__##

## Step 1: Creating NumPy Arrays

- Create multiple dimensional arrays, such as 1D, 2D and 3D
- Print the dimension and shapes of those NumPy arrays


Let's first import the NumPy package:

In [ ]:
import numpy as np

## Step 2: Create a 0D Array
- Use the dot array method
- Pass a scalar value to it, such as 24

In [ ]:
np.array(24)

array(24)

**Observation:**
- 0D arrays are scalars where each scalar value can be considered an element of the array, such as 24. 

## Step 3: Creating a 1D Array
- 1D arrays are unidimensional and have 0D arrays as its elements.



Let's create a 1D array:

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

##Step 4: Creating a 2D Array
- 2D arrays have 1D arrays as their elements.
- They are also called 2nd order tensors.
- They are often used to represent matrices.

Let's create a 2D array:

In [ ]:
np.array([[1,1,1],[1,2,1]])

array([[1, 1, 1],
       [1, 2, 1]])

## Step 5: Creating a 3D Array
- 3D arrays have 2D arrays as their elements.

In [ ]:
np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

##Step 6: Checking the Dimension and Shape of an Array


Let's create a 3-D array using np.array():

In [ ]:
numpy_arr = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

Now, display the shape of the array using .shape:

In [ ]:
numpy_arr.shape

(2, 2, 3)

**Observation:**
- The shape of a 3D array is (2, 2, 3).


Then, display the number of dimensions in the array using .ndim:

In [ ]:
numpy_arr.ndim

3

**Observation:**
- The array is a three-dimensional array.


##Step 7. Creating an Array with a Desired Number of Dimensions


Let's create a five-dimensional NumPy array using the **ndmin** parameter:

In [ ]:
np.array([1,2,3,4,5],ndmin = 5)

array([[[[[1, 2, 3, 4, 5]]]]])

Now, print the number of dimensions of the array mentioned in above cell:

In [ ]:
array= np.array([1,2,3,4,5],ndmin = 5)
array.ndim

5