## __Indexing and Slicing NumPy Arrays in Python__

## Slicing
- Slicing refers to selecting a subset of elements from a sequence by specifying a start index and an end index. 


##Step 1: Import the NumPy Library and Create Arrays

Let's import the NumPy library:

In [ ]:
import numpy as np

Now, let's create 1D, 2D and 3D NumPy arrays.


In [ ]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

## Step 2: Slicing 1D NumPy Arrays


To slice the 1D NumPy array, first display the 1D array:




In [ ]:
array_1d

array([1, 2, 3, 4, 5, 6])

Then, extract the elements: from the second (inclusive) element to the end:

In [ ]:
array_1d[1:]

array([2, 3, 4, 5, 6])

Then, extract elements: from the fourth (inclusive) element to the sixth (exclusive):

In [ ]:
array_1d[3:5]

array([4, 5])

Now, extract elements: from the fourth (inclusive) element to the sixth (exclusive) using negative slicing:

In [ ]:
array_1d[-3:-1]

array([4, 5])

## Step 3: Slicing 2D NumPy Arrays

For slicing the 2D array, let's first display the 2D array:


In [ ]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

Then, extract the elements: from the second row and second column (inclusive) to the end:

In [ ]:
array_2d[1,1:]

array([5, 6])

Then, extract the first row of the 2D array in reverse order:

In [ ]:
array_2d[-2:-3:-1]

array([[1, 2, 3]])

## Step 4: Slicing 3D NumPy Arrays

To slice the 3D array, let's display the 3D array first:


In [ ]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Now, we will extract the elements from the first matrix (index 0), select row 2 and then select the elements from column 2 until the end of the row.

In [ ]:
array_3d[0,1:,1:]

array([[5, 6]])