## __Arithmetic Operations in Python__

## Step 1: Arithmetic Operations using **NumPy**

Let's import the NumPy library: 

In [ ]:
import numpy as np

Create two NumPy arrays using np.array():

In [ ]:
A = np.array([[1,2,1],[2,2,3]])
B = np.array([3,4,5])

Display the arrays using their variable names:

In [ ]:
A

array([[1, 2, 1],
       [2, 2, 3]])

In [ ]:
B

array([3, 4, 5])

##Step 2: Addition
Now, perform element-wise addition of 'A' and 'B' using the 'np.add' method:

In [ ]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

**Observation:**
- The result presented above is obtained by adding the two NumPy arrays.

##Step 3: Subtraction
Now, perform element-wise subtraction of 'A' from 'B' using the 'np.subtract' method:

In [ ]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

**Observation:**

- The result presented above is obtained by subtracting one of the NumPy arrays from the other.

##Step 4: Multiplication
Now, perform element-wise multiplication of 'A' and 'B' using the 'np.multiply' method:

In [ ]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

**Observation:**

- The result presented above is obtained by multiplying the two NumPy arrays.
- Remember, this multiplication is an element-wise multiplication not a matrix-type multiplication.

##Step 5. Division
- Now, perform element-wise division of 'A' by 'B' using the 'np.divide' method:

In [ ]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

**Observation:**

- The result presented above is obtained by dividing one of the NumPy arrays by the other.

##Step 6: Power Of
Now, let's raise one array to the power of '2' using the np.power() method:



In [ ]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]])

**Observation:**

- The result presented above shows the square of all the elements in the array.

Perform element-wise power operation where each element in 'A' is raised
to the corresponding element in 'B' using the 'np.power' method:

In [ ]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]])

**Observation:**

- The result presented above shows the NumPy array 'A' raised to the power of other array 'B'.